### ISSUE TITLE
Can't click on "Add Host"

### ISSUE THREAD

**Issue by Flarkk** [OneLiberty/moonlight-tizen-nacl#3]
Device : Smart TV Samsung The Frame 2017 (UE43LS003)
TV Software version : T-KTMDEUC-1401.1 , BT-S
Followed the readme instructions to install the app on the TV with the docker image.
I haven't checked it but I assume the app version I installed is commit [dafccf7](https://github.com/OneLiberty/moonlight-tizen-nacl/commit/dafccf74eb55df4d5a1438bc95d9cdf5fc9d6b00)

Fresh install of the app, first launch.
On the client home screen, clicking on "Add Host" has no effect.
Clicking on the top right corner options (resolution, FPS, bandwidth, audio, mouse, ...) does work and allows changing the values.
Clicking on "Quit Current App" (top-right corner) or the left-pointing arrow next to the "MoonLight" logo (top-left corner) has no effect.

I tried out using the remote control, an usb mouse plugged into the tv, and the SmartView app on my smartphone. None of them work.

Happy to share logs or anything that matters if you guide through. I'm not familiar with Tizen OS nor  its command line interface.

**Comment by OneLiberty** [comment]
Uh oh. 
I guess the app is not compatible with tizen 3.0... 
Sorry about that, can't do much tho. 
Maybe you can try getting the logs (https://github.com/OneLiberty/moonlight-chrome-tizen/discussions/9)

**Comment by Flarkk** [comment]
I'm blocked at the step where I'm supposed to execute `sdb shell 0 debug "MoonLightS.MoonlightWasm"`.
The terminal prompts back `closed`.
I suspect the name of the application is different in the case of the NaCl version.
Any hint ?

**Comment by Flarkk** [comment]
@OneLiberty thanks.
I think I got the console working, however I can't see any log message even when I interact with the app on the TV.
Am I doing anything wrong ?
![image](https://github.com/user-attachments/assets/fe06a1ae-9bb1-4215-a417-c52b23054bc3)

**Comment by MrPhaze62** [comment]
you are on the right track, in that screenshot on that browser, the logs should be displayed under 'console' tab there.

if it still doesnt show up, i have been guided by oneliberty to use an older version of chrome that shows the logs in that tab.

once the logs are displayed, press a few buttons on moonlight on your tv, and hopefully the errors should show up in real time, to which youll be able to highlight the logs and copy and paste it here.

(occasionally, chrome or whatever browser you are using may crash since it will continuously output logs in real time. has happened often with me, lol)

i will point out, i have been using docker desktop instead of tizen studio to get logs, but the method should be similar. more or less.

Just to point out, that guide linked by OneLiberty was made for the WASM port to grab logs, since this is NaCl. Only one cmd should be replaced which is:

sdb shell 0 debug "ChqHQExU28.MoonlightNaCl" 0

Instead of the one mentioned in the guide.
Seems like you may already know this, but i will point it out for others that use this NaCl port for older samsung tvs.

**Comment by OneLiberty** [comment]
Check out the "Console" Tab on the logs
If it's showing usually it should work, but if not, maybe you want to try an older version of chrome (prior to the TV release so maybe a 2016 build or smt)

**Comment by ProgressoRU** [comment]
Just stumbled on this project while looking for suitable Steam Link replacement and unfortunately got same issue.  After some debugging and troubleshooting I've gathered some (hopefully) useful logs:
```
index.js:855 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
navigation.js:2 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
utils.js:93 Uncaught SyntaxError: Unexpected token =
controllers.js:2 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
common.js:331 [updateStatus, common.js] Page loaded..
```

So, basically every modern JS feature = BAD
![изображение](https://github.com/user-attachments/assets/6772b58a-cb87-4dde-8027-526a47ef7282)

TV Model: UE40MU6470 (2017)

For anyone who will try to debug on the older Tizens: I've used Chrome 49 to get Dev Tools working and you should run sdb shell command like this: `sdb shell 0 debug "ChqHQExU28.MoonlightNaCl" 0` (note added zero at the end)

**Comment by JoanOrtiga** [comment]
Hey, I have Tizen 3.0 too and basically the UI doesn't respond at all :/

**Comment by OneLiberty** [comment]
Well there are few hints on where to look to make it maybe work on tizen 3.0 with @ProgressoRU comment. 
If anyone is able to make the changes and test, that would be nice.

**Comment by CSharpRU** [comment]
After fixes to JS got it working properly, but it streams 720p 30fps only, so better to buy HDMI :)
(see https://github.com/OneLiberty/moonlight-chrome-tizen/issues/7)

Can attach changes if you want tho.

**Comment by OneLiberty** [comment]
> After fixes to JS got it working properly, but it streams 720p 30fps only, so better to buy HDMI :)
> 
> (see https://github.com/OneLiberty/moonlight-chrome-tizen/issues/7)
> 
> 
> 
> Can attach changes if you want tho.

Great ! 

Well it's better than nothing ! 
You can make a PR if you want 
Else, I'll need to reimplement the changes myself.

**Comment by CSharpRU** [comment]
> > After fixes to JS got it working properly, but it streams 720p 30fps only, so better to buy HDMI :)
> > (see [OneLiberty/moonlight-chrome-tizen#7](https://github.com/OneLiberty/moonlight-chrome-tizen/issues/7))
> > Can attach changes if you want tho.
> 
> Great !
> 
> Well it's better than nothing ! You can make a PR if you want Else, I'll need to reimplement the changes myself.

There you go https://github.com/OneLiberty/moonlight-tizen-nacl/pull/4

**Comment by MrPhaze62** [comment]
Heh, i wonder if that fix works on tizen 2.4
Would be cool lol.

**Comment by CSharpRU** [comment]
> Heh, i wonder if that fix works on tizen 2.4 Would be cool lol.

Should work

**Comment by Flarkk** [comment]
I confirm the fix solves this issue with tizen 3.
The UI is fully functional now.
And I don't experience the streaming resolution / fps limitations mentioned above.
I works well at 1080p 60fps on my tv.
Thanks @CSharpRU for the fix !

**Comment by CSharpRU** [comment]
> I confirm the fix solves this issue with tizen 3. The UI is fully functional now. And I don't experience the streaming resolution / fps limitations mentioned above. I works well at 1080p 60fps on my tv. Thanks @CSharpRU for the fix !

Lucky you, my version of Tizen might be earlier than yours and thus doesn't work as intended :)

**Comment by OneLiberty** [comment]
@CSharpRU I'm guessing you're running a 2.3/2.4 TV then 
I've got one at home too, I think the webengine is different (not chromium) 
So it might not even have NaCl (not sure, I'll have to confirm) 
But regardless, the JS require even more work than what you did ! 

Still this is a good thing for tizen 3.0 users ! Thanks again

**Comment by CSharpRU** [comment]
> @CSharpRU I'm guessing you're running a 2.3/2.4 TV then I've got one at home too, I think the webengine is different (not chromium) So it might not even have NaCl (not sure, I'll have to confirm) But regardless, the JS require even more work than what you did !
> 
> Still this is a good thing for tizen 3.0 users ! Thanks again

Nope, Tizen 3, 2016 TV UE43 something :) But glad it works for you.

**Comment by OneLiberty** [comment]
Mb, maybe it's related to the ethernet issue we have on the WASM port then, is the TV connected on Wifi ?

**Comment by CSharpRU** [comment]
> Mb, maybe it's related to the ethernet issue we have on the WASM port then, is the TV connected on Wifi ?

Cable.

**Comment by OneLiberty** [comment]
I'd suggest trying with WiFi
