### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by michlq** [OneLiberty/moonlight-tizen-nacl#5]
hello. 
I can't connect to the TV. The following error occurs:

PS C:\Windows\System32\WindowsPowerShell\v1.0> docker run -it --rm ghcr.io/oneliberty/moonlight-tizen-nacl:samsung_nacl
Unable to find image 'ghcr.io/oneliberty/moonlight-tizen-nacl:samsung_nacl' locally
samsung_nacl: Pulling from oneliberty/moonlight-tizen-nacl
4f4fb700ef54: Already exists
7478e0ac0f23: Download complete
d878fea2864f: Download complete
Digest: sha256:14368fbca14dbc0e0d9a8d36b18645584d7666bc07fc4567e8cbe1b5bf5a5a7c
Status: Downloaded newer image for ghcr.io/oneliberty/moonlight-tizen-nacl:samsung_nacl
moonlight@760a92ed0d2d:~$ sdb connect 192.168.18.22
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.18.22:26101 ...
failed to connect to 192.168.18.22:26101
moonlight@760a92ed0d2d:~$

the ip of the tv is the right one. 
dev options on the tv are also activated

**Comment by OneLiberty** [comment]
This looks like a local network issue, be sure to be on the same network 
Reboot the TV via a long press (10s) 
Double check the TV ip, and the PC IP (that you should have entered in the dev option menu on the TV).

**Comment by michlq** [comment]
> This looks like a local network issue, be sure to be on the same network Reboot the TV via a long press (10s) Double check the TV ip, and the PC IP (that you should have entered in the dev option menu on the TV).

thank you. after resart the complete network it works
